const TRADICIONAL_1 = {id: "TORTA DE CHOCLATE", precio: 29.900};
const TRADICIONAL_2 = {id: "TORTA DE FRUTOS ROJOS", precio: 29.900};
const TRADICIONAL_3 = {id: "PASTEL RED LABEL", precio: 29.900};
const TRADICIONAL_4 = {id: "PASTEL DELICIOUS RED", precio: 29.900};

const REFIJERADAS_1 = {id: "PASTEL DE BELÉM", precio: 34.900};
const REFIJERADAS_2 = {id: "PASTEL DE ALFAJOR", precio: 34.900};
const REFIJERADAS_3 = {id: "TARTA DE CHOCOLATE", precio: 34.900};
const REFIJERADAS_4 = {id: "TORTA DE CEREZA", precio: 34.900};

const POSTRES_1 = {id: "FLAN DE CHOCOLATE", precio: 42.900};
const POSTRES_2 = {id: "CUPCAKES", precio: 27.900};
const POSTRES_3 = {id: "POSTRE DE FRUTAS", precio: 39.900};
const POSTRES_4 = {id: "POSTRE RASPBERRY DESSERT", precio: 29.900};

const CATALOGO_TRADICIONAL = [TRADICIONAL_1, TRADICIONAL_2, TRADICIONAL_3, TRADICIONAL_4];
const CATALOGO_REFRIJERADAS = [REFIJERADAS_1, REFIJERADAS_2, REFIJERADAS_3, REFIJERADAS_4];
const CATALOGO_POSTRES = [POSTRES_1, POSTRES_2, POSTRES_3, POSTRES_4];






